name: Build/Test Code

on:
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Setup App
        run: npm ci --ignore-scripts
      - name: Test App (Unit Tests)
        run: npm test
      - name: Lint App
        run: npm run lint
      - name: Build App
        run: npm run build --if-present
